### ISSUE TITLE
ask a question

### ISSUE THREAD

**Issue by ReeseZeng** [alikaraali/TIP2018-Edge-Based-Defocus-Blur-Estimation-With-Adaptive-Scale-Selection#1]
Excuse me, is there lack of the M file about the definition of  RF function? because the codes don't work. Thank you.

**Comment by alikaraali** [comment]
Hello,
Thank you for your interest! As explained in the README file, related .M files (such as RF)  should be downloaded. The link is in the README.
Best

**Comment by ReeseZeng** [comment]
Thank you for your explanation, and sorry for my carelessness.




------------------ 原始邮件 ------------------
发件人: "Ali Karaali"<notifications@github.com>;
发送时间: 2018年5月16日(星期三) 凌晨1:43
收件人: "alikaraali/TIP2018-Edge-Based-Defocus-Blur-Estimation-With-Adaptive-Scale-Selection"<TIP2018-Edge-Based-Defocus-Blur-Estimation-With-Adaptive-Scale-Selection@noreply.github.com>;
抄送: "曾志鹏"<404895321@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re:[alikaraali/TIP2018-Edge-Based-Defocus-Blur-Estimation-With-Adaptive-Scale-Selection]ask a question (#1)




Hello,
 Thank you for your interest! As explained in the README file, related .M files (such as RF)  should be downloaded. The link is in the README.
 Best

**Comment by alikaraali** [comment]
No problem, your welcome!
