### ISSUE TITLE
How to test on my own dataset.

### ISSUE THREAD

**Issue by ListenInTheDark** [alikaraali/TIP2018-Edge-Based-Defocus-Blur-Estimation-With-Adaptive-Scale-Selection#2]
Hi, this work is cool. I am very sorry to bother you. I want to know if this code can test on my own dataset and I look forward to your reply.

**Comment by alikaraali** [comment]
Hello, 

Sorry for the late reply. Yes, the code can be run on any dataset. 

Best

**Comment by alikaraali** [comment]
Just run the code as follows;
```
Iuint = imread('any_image');
Idouble = im2double(Iuint);
[blurMap, ~ , ~] = blur_estimate_our(Idouble);
figure; imagesc(blurMap);
```
