### ISSUE TITLE
Poor results on self-synthesized NYU_V2 dataset

### ISSUE THREAD

**Issue by fuy34** [alikaraali/TIP2018-Edge-Based-Defocus-Blur-Estimation-With-Adaptive-Scale-Selection#3]
Hi, 

thanks for sharing the code. 

I tried it with a self-synthesized nyu_v2 dataset, using the code from [d3Net](https://github.com/marcelampc/d3net_depth_estimation/tree/master/matlab), where the ground truth defocus is calculated based on the well-known relationship between circle of confusion and depth.  I simply follow the instruction on [issue#2](https://github.com/alikaraali/TIP2018-Edge-Based-Defocus-Blur-Estimation-With-Adaptive-Scale-Selection/issues/2#issuecomment-490918443) and test on MATLAB 2018b. But the results looks quite poor. 

One example is attach below whose MSE=1.333.

Did I miss something here? 
Thanks in advance. 

![image](https://user-images.githubusercontent.com/42375440/88358583-823daa80-cd3d-11ea-9934-5338b3f5802a.png)

**Comment by alikaraali** [comment]
Hello Fengting,

Thank you for reaching me out. I believe the images that you use to feed the method do not provide enough/good edges for the proposed method. We mentioned about this limitation in the paper.

I hope this helps.

Best
Ali
